@InventoryExport.Api_HostAddress = http://localhost:5087

GET {{InventoryExport.Api_HostAddress}}/api/users?page=1&pageSize=10
Accept: application/json

###

GET {{InventoryExport.Api_HostAddress}}/api/inventory-items?page=1&pageSize=10&type=Laptop
Accept: application/json

###

GET {{InventoryExport.Api_HostAddress}}/api/export/pdf?template=Classic&type=Laptop
Accept: application/pdf

###
